#!/bin/bash

echo "Copying module files"
mkdir -p ./build/csinterp/node_modules/
cp -r ./node_modules/antlr4/src/antlr4/ ./build/csinterp/node_modules/

echo Converting C# Builtin Libraries into Typescript
generatedBuiltinCSharpLibraryPath=./src/generated-builtinCSharpLibraries
if [ -d $generatedBuiltinCSharpLibraryPath ]; then
    rm -r $generatedBuiltinCSharpLibraryPath
fi
mkdir $generatedBuiltinCSharpLibraryPath
for csharpLibrary in "./BuiltinCSharpLibraries/*.cs"; do
    csharpFileName=$(basename $csharpLibrary)
    destinationFile="$generatedBuiltinCSharpLibraryPath/$csharpFileName.ts"
    echo "// This is a generated file. Do not edit this file directly." >> $destinationFile
    echo "// Edit the C# source file ../../BuiltinCSharpLibraries/$csharpFileName then use the build script to regenerate this file." >> $destinationFile
    echo "const csharpCode = \`" >> $destinationFile
    csharpCodeContent=$(cat $csharpLibrary)
    echo $csharpCodeContent >> $destinationFile
    echo "\`;" >> $destinationFile
    echo "export default csharpCode;" >> $destinationFile
    echo "    Converted $csharpFileName into $destinationFile"
done

echo Building TypeScript
npm run build_src
echo Build complete