@echo off
setlocal enabledelayedexpansion

echo Copying module files
xcopy ".\node_modules\antlr4\src\antlr4\" ".\build\csinterp\node_modules\antlr4\" /s /e /y

echo Converting C# Builtin Libraries into Typescript
set generatedBuiltinCSharpLibraryPath=.\src\generated-builtinCSharpLibraries
if exist %generatedBuiltinCSharpLibraryPath% (rmdir /s /q %generatedBuiltinCSharpLibraryPath%)
mkdir %generatedBuiltinCSharpLibraryPath%
for %%i in (".\BuiltinCSharpLibraries\*.cs") do (
    set destinationFile=%generatedBuiltinCSharpLibraryPath%\%%~nxi.ts
    echo // This is an auto-generated file. Do not edit this file directly. > !destinationFile!
    echo // Edit the C# source file ..\..\BuiltinCSharpLibraries\%%~nxi then use the build script to regenerate this file. >> !destinationFile!
    echo const csharpCode = ` >> !destinationFile!
    set csharpCodeContent=
    for /f "usebackq delims=" %%c in (%%i) do (
        set csharpCodeContent=!csharpCodeContent!%%c
    )
    echo !csharpCodeContent! >> !destinationFile!
    echo `; >> !destinationFile!
    echo export default csharpCode; >> !destinationFile!
    echo     Converted %%i into !destinationFile!
)


echo Building TypeScript
call npm run build
echo Build complete
pause