const BUILD_OUTPUT_DIR_RELATED_TO_SRC = '../build/csinterp';
const TEST_CASES_DIR_RELATED_TO_SRC = '__tests__util/testcases';

module.exports = {
	"BUILD_OUTPUT_DIR_RELATED_TO_SRC" : BUILD_OUTPUT_DIR_RELATED_TO_SRC,
	"TEST_CASES_DIR_RELATED_TO_SRC" : TEST_CASES_DIR_RELATED_TO_SRC
};